version: '3'
services:
  slim:
    platform: linux/amd64
    build:
      context: . 
      args:
        # New Relic agent will send data on https://<domain_of_cubeapm_server>:443
        NEW_RELIC_HOST: <domain_of_cubeapm_server>
    container_name: cube_php_slim
    environment:
      - PHP_CLI_SERVER_WORKERS=4
    ports:
      - "8000:80"  
    depends_on:
      - mysql
      - redis
    restart: always
  
  mysql:
    image: mysql:8.0
    container_name: cube_php_slim_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_php_slim_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_php_slim_redis

volumes:
    cube_php_slim_mysql:
    